apiVersion: v2
name: well-known
description: A Helm chart for Kubernetes
type: application
version: 1.9.0
appVersion: 1.9.0
maintainers:
  - email: dries@stenic.io
    name: Stenic
home: https://github.com/stenic/well-known/tree/main/charts/well-known
sources:
  - https://github.com/stenic/well-known
keywords:
  - well-known
